# Generated by Django 3.2.10 on 2023-04-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(blank=True, max_length=100, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
