# Generated by Django 3.2.10 on 2023-04-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(blank=True, max_length=100, null=True)),
                ('DepartmentName', models.CharField(blank=True, max_length=100, null=True)),
                ('Speciality', models.CharField(blank=True, max_length=100, null=True)),
                ('About', models.CharField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Profile1')),
                ('Overview', models.CharField(blank=True, max_length=1000, null=True)),
                ('Awards_Recognition', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
