# Generated by Django 3.2.10 on 2023-05-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
