# Generated by Django 3.2.10 on 2023-05-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0006_rename_departmentname_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Name',
            new_name='DepartmentName',
        ),
    ]
