# Generated by Django 3.2.10 on 2023-05-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0007_rename_name_department_departmentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='Profile'),
        ),
    ]
