# Generated by Django 3.2.10 on 2023-05-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0008_department_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Image1',
        ),
    ]
